# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import json, os


SHIB_LOGIN_URL = os.environ['EZACS__ARTICLE_REQUEST_SHIB_LOGIN_URL']
SHIB_LOGOUT_URL_ROOT = os.environ['EZACS__COMMON_SHIB_LOGOUT_URL_ROOT']

DEVELOPMENT_SHIB_DCT = json.loads( os.environ['EZACS__COMMON_DEVELOPMENT_SHIB_JSON'] )

ILLIAD_REMOTE_AUTH_URL = os.environ['EZACS__ARTICLE_REQUEST_ILLIAD_REMOTE_AUTH_URL']
ILLIAD_REMOTE_AUTH_HEADER = os.environ['EZACS__ARTICLE_REQUEST_ILLIAD_REMOTE_AUTH_HEADER']

EMAIL_FROM = os.environ['EZACS__ARTICLE_REQUEST_EMAIL_FROM']

## for tests ##

TEST_ILLIAD_GOOD_USERNAME = os.environ['EZACS__ARTICLE_REQUEST_TEST_ILLIAD_GOOD_USERNAME'].decode( 'utf-8' )
TEST_ILLIAD_NEW_USER_ROOT = os.environ['EZACS__ARTICLE_REQUEST_TEST_ILLIAD_NEW_USERNAME_ROOT'].decode( 'utf-8' )
