# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import json, os


SHIB_LOGIN_URL = os.environ['EZACS3__ARTICLE_REQUEST_SHIB_LOGIN_URL']
SHIB_LOGOUT_URL_ROOT = os.environ['EZACS3__COMMON_SHIB_LOGOUT_URL_ROOT']
SHIB_LOGOUT_URL_RETURN_ROOT =  os.environ['EZACS3__ARTICLE_REQUEST_SHIB_LOGOUT_URL_RETURN_ROOT']

DEVELOPMENT_SHIB_DCT = json.loads( os.environ['EZACS3__COMMON_DEVELOPMENT_SHIB_JSON'] )

ILLIAD_REMOTE_AUTH_URL = os.environ['EZACS3__ARTICLE_REQUEST_ILLIAD_REMOTE_AUTH_URL']
ILLIAD_REMOTE_AUTH_HEADER = os.environ['EZACS3__ARTICLE_REQUEST_ILLIAD_REMOTE_AUTH_HEADER']

EMAIL_FROM = os.environ['EZACS3__ARTICLE_REQUEST_EMAIL_FROM']

REQUIRED_GROUPER_GROUP =  os.environ['EZACS3__BORROW_REQUIRED_GROUP']
PERMISSION_DENIED_PHONE =  os.environ['EZACS3__BORROW_PERMISSION_DENIED_PHONE']
PERMISSION_DENIED_EMAIL =  os.environ['EZACS3__BORROW_PERMISSION_DENIED_EMAIL']

ILLIAD_API_URL_ROOT =  os.environ['EZACS3__COMMON_ILLIAD_API_URL_ROOT']  # internal brown illiad-api web-service
ILLIAD_API_KEY =  os.environ['EZACS3__COMMON_ILLIAD_API_KEY']  # for posts

ILLIAD_API_BASIC_AUTH_USER = os.environ['EZACS3__COMMON_ILLIAD_API_BASIC_AUTH_USER']  # for gets
ILLIAD_API_BASIC_AUTH_PASSWORD = os.environ['EZACS3__COMMON_ILLIAD_API_BASIC_AUTH_PASSWORD']


## for tests ##

TEST_ILLIAD_GOOD_USERNAME = os.environ['EZACS3__ARTICLE_REQUEST_TEST_ILLIAD_GOOD_USERNAME']
TEST_ILLIAD_DISAVOWED_USERNAME = os.environ['EZACS3__ARTICLE_REQUEST_TEST_ILLIAD_DISAVOWED_USERNAME']
TEST_ILLIAD_BLOCKED_USERNAME = os.environ['EZACS3__ARTICLE_REQUEST_TEST_ILLIAD_BLOCKED_USERNAME']

TEST_ILLIAD_NEW_USER_ROOT = os.environ['EZACS3__ARTICLE_REQUEST_TEST_ILLIAD_NEW_USERNAME_ROOT']

TEST_GOOD_USRDCT = json.loads( os.environ['EZACS3__ARTICLE_REQUEST_TEST_GOOD_USRDCT_JSON'] )
